-- 001_schema.sql — Supabase migration for Football Calendar
-- Creates 7 tables, indexes, and RLS policies for the data pipeline.
-- Apply via: supabase migration up (or paste in Supabase SQL Editor)

-- ── Extensions ──────────────────────────────────────────────────────────────

create extension if not exists "pgcrypto";

-- ── Reference Tables (seeded once) ──────────────────────────────────────────

-- Leagues: supported football competitions
create table leagues (
  id            int primary key generated by default as identity,
  api_id        int unique not null,            -- API-Football league ID
  name          text not null,
  logo          text,                           -- League logo URL (nullable, populated by seed/fetch)
  season        int not null,                   -- Current season year (e.g. 2026)
  group_name    text not null,                  -- Display group: 'Mundial', 'Inglaterra', etc.
  display_order int not null default 99,
  default_sel   boolean not null default true   -- Pre-selected in league filter
);

-- Teams: football clubs and national teams
create table teams (
  id       int primary key generated by default as identity,
  api_id   int unique not null,                 -- API-Football team ID
  name     text not null,
  logo     text                                 -- Team logo URL
);

-- Team Rosters: many-to-many league-team membership per season
create table team_rosters (
  league_id int references leagues(id) on delete cascade,
  team_id   int references teams(id) on delete cascade,
  season    int not null,
  primary key (league_id, team_id, season)
);

-- Bracket Nodes: World Cup knockout bracket layout (seeded once)
create table bracket_nodes (
  id               text primary key,            -- e.g. 'M73', 'R16-M1', 'QF-M3', 'SF-M2', 'F-M1'
  round            text not null,               -- 'R32' | 'R16' | 'QF' | 'SF' | 'F'
  round_index      int not null,                -- 0=R32, 1=R16, 2=QF, 3=SF, 4=F
  matchup_index    int not null,                -- Position within round (visual display order)
  home_source      text,                        -- Source of home team: '1°E', 'M74' (previous winner), etc.
  away_source      text,                        -- Source of away team or null for third-place slots
  is_third_place   boolean not null default false,
  candidate_groups text,                        -- 'A,B,C,D,F' for third-place slots (comma-separated)
  grid_row_start   int,                         -- CSS Grid row start
  grid_row_span    int,                         -- CSS Grid row span
  grid_col         int                          -- CSS Grid column
);

-- ── Dynamic Tables (upserted by Edge Function) ──────────────────────────────

-- Matches: fixtures with scores and status
create table matches (
  id             text primary key,               -- API-Football fixture.id
  league_id      int references leagues(id) on delete cascade,
  season         int not null,
  round          text,                           -- e.g. 'Group Stage', 'Round of 16', 'Quarter-finals'
  round_order    int,                            -- Numeric ordering for rounds
  home_team_id   int references teams(id) on delete cascade,
  away_team_id   int references teams(id) on delete cascade,
  date           timestamptz not null,
  status         text not null default 'scheduled', -- 'scheduled' | 'live' | 'finished' | 'extra_time' | 'penalty'
  home_score     int,                            -- Null until match starts
  away_score     int,                            -- Null until match starts
  minute         int,                            -- Elapsed minutes (for live matches)
  is_knockout    boolean not null default false,
  venue          text,                           -- Stadium name
  elapsed        int,                            -- Total elapsed minutes
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);

create index idx_matches_date   on matches(date);
create index idx_matches_league on matches(league_id);
create index idx_matches_status on matches(status);

-- Standings: league and group standings
create table standings (
  id             serial primary key,
  league_id      int references leagues(id) on delete cascade,
  season         int not null,
  group_name     text not null,                  -- 'A'..'L' for World Cup, 'League' for single-table leagues
  team_id        int references teams(id) on delete cascade,
  rank           int not null,
  points         int not null default 0,
  played         int not null default 0,
  wins           int not null default 0,
  draws          int not null default 0,
  losses         int not null default 0,
  goals_for      int not null default 0,
  goals_against  int not null default 0,
  goal_diff      int not null default 0,
  form           text,                           -- Recent form: 'W,D,L,W,W' (nullable)
  updated_at     timestamptz not null default now(),
  unique(league_id, season, group_name, team_id)
);

create index idx_standings_ls on standings(league_id, season);

-- Pipeline Meta: scheduler state for the Edge Function (single row)
create table pipeline_meta (
  id             int primary key default 1,
  last_fetched   timestamptz,                    -- When the last fetch completed
  next_planned   timestamptz,                    -- When the next fetch is scheduled
  known_fixtures jsonb,                          -- Cached fixture metadata for scheduling decisions
  mode           text not null default 'worldcup', -- 'worldcup' | 'leagues' | 'full' | 'live' | 'off'
  error_count    int not null default 0,
  last_error     text,
  updated_at     timestamptz not null default now(),
  constraint one_row check (id = 1)
);

-- Seed the initial pipeline_meta row
insert into pipeline_meta (id, mode) values (1, 'worldcup');

-- ── Row Level Security ──────────────────────────────────────────────────────

-- Enable RLS on all tables
alter table leagues       enable row level security;
alter table teams         enable row level security;
alter table team_rosters  enable row level security;
alter table bracket_nodes enable row level security;
alter table matches       enable row level security;
alter table standings     enable row level security;
alter table pipeline_meta enable row level security;

-- Public read policies — anonymous users can SELECT from reference and data tables
create policy "Public read access" on leagues       for select using (true);
create policy "Public read access" on teams         for select using (true);
create policy "Public read access" on team_rosters  for select using (true);
create policy "Public read access" on bracket_nodes for select using (true);
create policy "Public read access" on matches       for select using (true);
create policy "Public read access" on standings     for select using (true);

-- pipeline_meta intentionally has no public policy:
-- RLS blocks anonymous reads by default. Only the Edge Function (service_role) can read/write it.
